name: Setup
description: Setup node project

runs:
  using: 'composite'
  steps:
    - name: Configure node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Get application version
      id: get_version
      run: echo "APP_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
      shell: bash

    - name: Set VITE_ENVIRONMENT
      run: echo "VITE_ENVIRONMENT=${{ job.environment.name }}" >> $GITHUB_ENV  
      shell: bash

    - name: Build project
      run: npm run build
      shell: bash
      env:
        APP_VERSION: ${{ env.APP_VERSION }}
        VITE_ENVIRONMENT: ${{ env.VITE_ENVIRONMENT }}
