# <project_root>/.github/workflows/hello.yml

name: Deploy Rick and Morty application

on:
  push:
    branches:
      - master

jobs:
  app-setup:
    runs-on: ubuntu-latest 
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: ./github/actions/setup-projet

      - name: Install dependencies
        run: npm ci 

      - name: Lint code
        run: npm run lint  

      - name: Run tests
        run: npm test  

      - name: Build app
        run: npm run build  

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"

      - name: Deploy app to Vercel production env
        uses: ./github/actions/deploy-vercel
        with:
          mode: 'production'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}